name: Salesforce CI Deploy

on:
  push:
    branches:
      - main  # Make sure your branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --set-default

      - name: Deploy metadata to Salesforce
        run: sf project deploy start --source-dir force-app
